# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('sublevel', models.IntegerField()),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
