# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0002_auto_20170415_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='sublevel',
            field=models.IntegerField(default=1),
        ),
    ]
