# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0008_auto_20170417_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='level',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='level',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
