# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0010_auto_20170418_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
